### ISSUE TITLE
Add GH action workflow to publish code to NPM

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sql-query-identifier#10]
We can largely take the workflow for publishing from sqlectron-core, modified for this repo:

```
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```
